Here is a list of additional configurations that are needed to achieve full
compliance with the `WCAG`_ 2.2 guidelines.  Open OnDemand cannot ship with
as they may be site specific.


* `WCAG criterion 2.4.5 "Multiple Ways"`_: Centers need to enable the :ref:`show_all_apps_link configuration <show_all_apps_link>`
  to complete this criteria. In addition to enabling the link in the navbar, it may be helpful to call attention and link to it
  in your :ref:`homepage welcome message <change_welcome_html>`.
* `WCAG criterion 3.2.6 "Consistent Help"`_: Centers need to :ref:`extend the help menu <help_menu_guide>`
  to complete this criteria.


.. _WCAG: https://www.w3.org/WAI/standards-guidelines/wcag/
.. _WCAG criterion 3.2.6 "Consistent Help": https://www.w3.org/TR/WCAG22/#consistent-help
.. _WCAG criterion 2.4.5 "Multiple Ways": http://www.w3.org/TR/WCAG20/#navigation-mechanisms-mult-loc
